contato/urls.py
from django.urls import path
from contato.views import index, descricao, search, create

app_name = 'contato'

# Na lista abaixo criamos as urls, que fazm o link diretamente com as views entregando a informação a view realizar a requisição
# servidor.
urlpatterns = [
    path('search/', search, name='search'),
    path('', index, name='index'),

    # CRUD, a seguir temos um padrão que geralmente indicado para URLs em que o conteúdo é um CRUD
    path('<int:contact_id>/detail/', descricao, name='descricao'),
    path('create/', create, name='create'),
    # path('<int:contact_id>/update/', descricao, name='descricao'),
    # path('<int:contact_id>/delete/', descricao, name='descricao'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # Include, inclui a url do app no coração do projeto
    path('', include('contato.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contato/models.py
"""
Documentação dos models: https://docs.djangoproject.com/pt-br/4.2/topics/db/models/
Documentação sobre tipos de dados Django: https://docs.djangoproject.com/pt-br/4.2/ref/models/fields/#field-choices
"""
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Categoria(models.Model):
    # Uma das funções da classe meta é controlar o nome que é exibido para as tabelas admin e como elas se relacionam com um ou
    # mais dados ou seja verbose_name é o nome da tabela para 1 dado, verbose_name_plural é quando tem vários dados
    # Vídeo sobre traduções Django: https://www.youtube.com/watch?v=iIsLwz_vkzA
    # Documentação da classe Meta Django: https://docs.djangoproject.com/pt-br/4.2/ref/models/options/
    #
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Varias'

    desc_categ = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.desc_categ


class Contato(models.Model):
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(
        max_length=50, blank=True, verbose_name='Sobrenome')
    telefone = models.CharField(max_length=30)
    email = models.EmailField(max_length=254, blank=True)
    data_contato = models.DateTimeField(default=timezone.now)
    descricao = models.TextField(blank=True)
    mostra = models.BooleanField(default=True)
    foto = models.ImageField(blank=True, upload_to='fotos/%Y/%m/')
    cod_categ = models.ForeignKey(
        Categoria, on_delete=models.SET_NULL, blank=True, null=True
    )
    proprietario = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self) -> str:
        return f'{self.f_name} {self.l_name}'

contato/views/forms.py
from django.core.exceptions import ValidationError
from contato.models import Contato
from django import forms


class FormContato(forms.ModelForm):
    f_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Digite o Primeiro Nome'
            }
        ),
        label='Primeiro Nome',
        help_text='Texto de ajuda ao usuário'
    )
    # qualquer = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'placeholders': 'Campo aleatório'
    #         }
    #     ),
    #     label='Só para teste'
    # )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields['f_name'].widget.attrs.update(
        #     {'placeholder': 'Digite o Primeiro Nome',
        #     }
        # )

    class Meta:
        model = Contato
        fields = (
            'f_name',
            'l_name',
            'telefone',
            'email',
            'descricao',
            'cod_categ'
        )
        # widgets = {
        #     'f_name': forms.TextInput(
        #         attrs={
        #             'placeholder': 'Digite o Primeiro Nome',
        #             'name': 'Primeiro Nome'
        #         }
        #     )
        # }

    def clean(self):
        f_name = self.cleaned_data.get('f_name')
        l_name = self.cleaned_data.get('l_name')

        if f_name == l_name:
            msg = ValidationError(
                'Nome Iguais',
                code='invalid'
            )

            self.add_error(
                'f_name',
                msg
            )
            self.add_error(
                'l_name',
                msg
            )

        return super().clean()

    def clean_f_name(self):
        first_name = self.cleaned_data.get('f_name')

        if first_name == 'ABC':
            self.add_error(
                'f_name',
                ValidationError(
                    'Campo Inválido',
                    code='invalid'
                )
            )

        return first_name

contato/views/contato_forms.py
from django.shortcuts import render, get_object_or_404
from contato.views.forms import FormContato
from django.db.models import Q


def create(request):
    if request.method == 'POST':
        contexto = {
            'form': FormContato(data=request.POST)
        }

        return render(
            request,
            'contato/create.html',
            contexto,
        )

    contexto = {
        'form': FormContato()
    }

    return render(
        request,
        'contato/create.html',
        contexto,
    )

contato/views/contato_views.py
# Documentação para classe do Django paginação: https://docs.djangoproject.com/en/4.2/topics/pagination/
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from contato.models import Contato
from django.db.models import Q

# Create your views here.


# Criação de uma view, é basicamente o que envia a requisição para o servidor de quais informações serão acessadas, no caso abaixo
# teremos alguns filtros, um deles exibe apenas os registros que estão mesmo marcados para serem exibidos pelo administrador
# e o outro filtro é de ordem, coluna com sinal negativo significa ordem decrescente
def index(request):
    contatos = Contato.objects\
        .filter(mostra=True)\
        .order_by('-id')
    # Paginator é uma classe do Django que permite como o nome diz, criar paginação em busca de dados organizando melhor as infos
    paginacao = Paginator(contatos, 10)

    page_number = request.GET.get("page")
    page_obj = paginacao.get_page(page_number)
    # print(contatos.query)

    contexto = {
        'contatos': page_obj,
        'nome_contato': 'Search - '
    }

    return render(
        request,
        'contato/index.html',
        contexto,
    )

# Essa view de busca faz um tipo de configuração para o navegador ignorar certos tipos de buscas, por exemplo ao usar
# a função strip padrão do python ignoramos qualquer espaço em branco que seja colocado no campo de busca pelo usuário, aceitando
# apenas valores com caracteres, o get é para receber o valor que vem do name 'q' definido no template que contém as tags do input
# de busca, além disso podemos usar uma função do django para que se o usuário digite alguma sequência de caracteres seja
# redicionado para outro lugar, no caso se realizar uma busca em branco a função redirect encaminha para a home da página.

# https://docs.djangoproject.com/en/4.2/ref/models/querysets/#field-lookups - Define os filtros para realizar as buscas


def search(request):
    valor_busca = request.GET.get('q', '').strip()
    print(valor_busca)

    if valor_busca == "":
        return redirect('contato:index')

    contatos = Contato.objects\
        .filter(mostra=True)\
        .filter(
            Q(f_name__icontains=valor_busca) |
            Q(l_name__icontains=valor_busca) |
            Q(email__icontains=valor_busca) |
            Q(telefone__icontains=valor_busca)
        )\
        .order_by('-id')

    paginacao = Paginator(contatos, 10)

    page_number = request.GET.get("page")
    page_obj = paginacao.get_page(page_number)

    # print(contatos.query)

    contexto = {
        'contatos': page_obj,
        'nome_contato': 'Contato - ',
        'valor_busca': valor_busca
    }

    return render(
        request,
        'contato/index.html',
        contexto,
    )


def descricao(request, contact_id):
    # desc = Contato.objects.get(
    #     id=contact_id)  # .get busca um único valor

    # Função pronta para checar se algo existe, caso contrário levanta uma exceção
    desc = get_object_or_404(Contato.objects, id=contact_id, mostra=True)

    nome = f'{desc.f_name} - '

    contexto1 = {
        'desc': desc,
        'nome_contato': nome
    }

    return render(
        request,
        'contato/desc_contato.html',
        contexto1,
    )

contato/templates/contato/create.html
{% extends "global\base.html" %}

{% block content %}
  <div class="form-wrapper">
    <h2>Novo Contato</h2>
    <form 
      action="{% url "contato:create" %}"
      method="POST"
      enctype="multipart/form-data" 
    > <!--O enctype permite o envio tanto de dados quanto de arquivos -->

      {% csrf_token %}

      {% comment %} <table>
        {{ form.as_p }}
      </table> {% endcomment %}

      <div class="form-content">
        {% for field in form %}
          <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}
            {{field.errors}}

            {% if field.help_text %}
              <p class="help-text"> {{field.help_text}} </p>
            {% endif %}
          </div> 
        {% endfor %}
      </div>

      {% if form.non_field_errors %}
        <div class="form-content">
            <div class="form-group">
              <div class="message error">
                {{form.non_field_errors}}
              </div>
            </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Gravar</button>
        </div>
      </div>

    </form>
  </div>  
{% endblock content %}

contato/templates/contato/desc_contato.html
{% extends "global/base.html" %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ desc.f_name }} {{ desc.l_name }}
    </h1>

    <p><b>ID:</b> {{desc.id}}</p>
    <p><b>E-mail:</b> {{desc.email}}</p>
    <p><b>Fone:</b> {{desc.telefone}}</p>
    <p><b>Data de Cadastro:</b> {{desc.data_contato}}</p>
    <p><b>Descrição:</b> {{desc.descricao}}</p>
    <p><b>Categoria:</b> {{desc.cod_categ.desc_categ}}</p>
  </div>
{% endblock content %}

contato/templates/contato/index.html
{% extends "global/base.html" %} {% comment %}integra o arquivo html ao arquivo base onde está a estrurura{% endcomment %}

{% block content %} {% comment %} Dentro desse bloco vai tudo o que será trabalhado dentro da tag main{% endcomment %}
  {% if contatos %}
    <div class="responsive-table"> <!--Uma div que carregará uma tabela-->
      <table class="contacts-table"> <!--Tag tabela-->
        <caption class="table-caption"> <!--Seria algo como o título da tabela-->
          Contatos
        </caption>
        <thead> <!--Tag que indica que vai ter um cabeçalho na tabela-->
          <tr class="table-row table-row-header"> <!--Linha onde estarão as colunas cabeçalho-->
            <th class="table-header">ID</th> <!--Cada coluna do cabeçalho-->
            <th class="table-header">Primeiro Nome</th>
            <th class="table-header">Último Nome</th>
            <th class="table-header">Telefone</th>
            <th class="table-header">E-mail</th>
          </tr>
        </thead>

      <tbody>
        {% for contato in contatos %} <!--Faz um for na tabela de contatos iterando todos os registros da tabela-->
          <tr class="table-row"> <!--Linhas das tabela-->
            <td class="table-cel"> <!--Tag td é onde os dados serão exibidos cada uma refere-se ao tipo de dado da coluna-->
              <a 
                href="{% url 'contato:descricao' contato.id %}" 
                class="table-link">
                {{contato.id}} <!--Os dados de cada coluna-->
              </a>
            </td>
            <td class="table-cel">
              {{contato.f_name}}
            </td>
            <td class="table-cel">
              {{contato.l_name}}
            </td>
            <td class="table-cel">
              {{contato.telefone}}
            </td>
            <td class="table-cel">
              {{contato.email}}
            </td>
          </tr>
        {% endfor %} <!--Termina a iteração-->
      </tbody>
    </table>
  </div>
  {% else %}
    <div class="single-contact">
      <h1 class="single-contact-name">
        Nenhum Contato Encontrado
      </h1>
    </div>
  {% endif %}
{% endblock content %}